export enum FollowQueryKeys {
  GET_FOLLOWERS = "GET_FOLLOWERS",
  GET_FOLLOWING = "GET_FOLLOWING",
  GET_STATUS = "GET_STATUS",
  FOLLOW_USER = "FOLLOW_USER",
  UNFOLLOW_USER = "UNFOLLOW_USER",
  BLOCK_USER = "BLOCK_USER",
  UNBLOCK_USER = "UNBLOCK_USER",
}
