export enum PostQueryKey {
  GET_POSTS = "GET_POSTS",
  GET_POST = "GET_POST",
  GET_POST_BY_ID = "GET_POST_BY_ID",
  GET_RECENT_POST = "GET_RECENT_POST",
  CREATE_POST = "CREATE_POST",
  UPDATE_POST = "UPDATE_POST",
  DELETE_POST = "DELETE_POST",
}
