export enum UserQueryKeys {
  GET_CURRENT_USER = "GET_CURRENT_USER",
  GET_ALL_USERS = "GET_ALL_USERS",
  GET_SEARCH_VALUES = "GET_SEARCH_VALUES",
  GET_ALL_USER_COUNT = "GET_ALL_USER_COUNT",

  VERIFY_USER = "VERIFY_USER",
}
